const personalities: Record<string,string> = {
    caregiver: "I'm a caregiver with a big heart and a love for helping others",
    sage: "I'm a sage with wisdom to share and stories to tell",
    innocent: "I'm an innocent soul with a pure heart",
    jester: "I'm a jester, always ready to bring a smile",
    temptress: "I'm a temptress with a captivating charm",
    dominant: "I'm dominant, taking charge with confidence",
    submissive: "I'm submissive, gentle and accommodating",
    lover: "I'm a lover, spreading warmth and affection",
    nympho: "I'm a nympho, passionate and full of energy",
    mean: "I'm mean, with a sharp tongue and a quick wit",
    confidant: "I'm a confidant, trustworthy and loyal",
    experimenter: "I'm an experimenter, always curious and adventurous"
};

const occupations: Record<string,string> = {
    massage_therapist: "relaxing others as a massage therapist",
    dentist: "keeping smiles bright as a dentist",
    nutrionist: "promoting healthy living as a nutritionist",
    fitness_coach: "bringing the energy as a fitness coach",
    pharmacist: "dispensing health as a pharmacist",
    hairdresser: "styling hair as a hairdresser",
    makeup_artist: "bringing out beauty as a makeup artist",
    gynecologist: "caring for women's health as a gynecologist",
    librarian: "immersed in books as a librarian",
    secretary: "keeping things organized as a secretary",
    social_worker: "supporting others as a social worker",
    fashion_designer: "creating trends as a fashion designer",
    interior_designer: "designing beautiful spaces as an interior designer",
    cook: "whipping up delicious meals as a cook",
    stylist: "fashionably styling as a stylist",
    esthetician: "providing beauty treatments as an esthetician",
    designer: "creating designs as a designer",
    yoga_instructor: "teaching relaxation as a yoga instructor",
    flight_attendant: "ensuring safe flights as a flight attendant",
    doctor: "healing people as a doctor",
    nurse: "caring for patients as a nurse",
    teacher: "educating minds as a teacher",
    firefighter: "bravely fighting fires as a firefighter",
    police_officer: "protecting the community as a police officer",
    soldier: "serving the country as a soldier",
    dancer: "moving rhythmically as a dancer",
    musician: "creating music as a musician",
    spy: "living on the edge as a spy",
    plane_pilot: "soaring the skies as a plane pilot",
    professional_athlete: "excelling in sports as a professional athlete",
    movie_star: "shining on screen as a movie star",
    photographer: "capturing moments as a photographer",
    artist: "expressing creativity as an artist",
    scientist: "exploring discoveries as a scientist",
    writer: "crafting stories as a writer",
    lawyer: "advocating for justice as a lawyer",
    student: "learning and growing as a student",
    life_coach: "guiding others as a life coach",
    kindergarden_teacher: "nurturing young minds as a kindergarten teacher",
    florist: "arranging flowers as a florist",
    baker: "baking treats as a baker",
    jewelry_designer: "creating beautiful jewelry as a jewelry designer",
    astronaut: "exploring space as an astronaut",
    model: "strutting the runway as a model",
    personal_trainer: "motivating fitness as a personal trainer",
    barber: "styling cuts as a barber",
    executive_assistant: "keeping things running smoothly as an executive assistant",
    architect: "designing buildings as an architect",
    chef: "cooking gourmet meals as a chef",
    product_designer: "innovating products as a product designer",
    martial_arts_instructor: "teaching martial arts as an instructor",
    commercial_pilot: "flying commercial planes as a pilot",
    taxi_driver: "navigating the streets as a taxi driver",
    professor: "lecturing students as a professor",
    detective: "solving mysteries as a detective",
    constructor_worker: "building structures as a construction worker",
    plumber: "fixing pipes as a plumber",
    mechanic: "repairing vehicles as a mechanic",
    truck_driver: "hauling goods as a truck driver",
    software_developer: "coding software as a developer",
    journalist: "reporting news as a journalist"
};

const hobbiesDescriptions: Record<string,string> = {
    fitness: "staying fit with workouts",
    vlogging: "creating vlogs",
    traveling: "exploring new places",
    hiking: "hiking up trails",
    gaming: "gaming",
    parties: "attending parties",
    series: "binging on the latest series",
    anime: "diving into anime adventures",
    cosplay: "dressing up for cosplay",
    self_development: "working on self-development",
    writing: "writing stories",
    diy_crafting: "doing DIY crafts",
    veganism: "embracing veganism",
    photography: "capturing moments with photography",
    volunteering: "volunteering",
    cars: "admiring cool cars",
    art: "creating art",
    watching_netflix: "watching Netflix",
    manga_and_anime: "enjoying manga and anime",
    martial_arts: "practicing martial arts",
    weightlifting: "lifting weights",
    camping: "going camping",
    sailing: "sailing",
};

export const handleDescription = (personality: string, occupation: string, hobbies: string[]) => {
    const personalityDescription = personalities[personality.toLowerCase()] || "I'm someone with a unique personality";
    const occupationDescription = occupations[occupation.toLowerCase().replace(" ", "_")] || "rocking an interesting job";
    const hobbiesDescription = hobbies.map(hobby => hobbiesDescriptions[hobby.toLowerCase()]).join(", ") || "enjoying fun hobbies";

    return `Hey there! ${personalityDescription}. When I'm not ${occupationDescription}, you'll find me ${hobbiesDescription}.`;
};
