import { randomNumber } from "../randomNumber";

const locationMap: Record<string, string> = {
  bikini: "on a sunny beach",
  skirt: "in a trendy cafe",
  cheerleader: "at a school sports event",
  pencil_dress: "at a formal office",
  long_dress: "at a grand ballroom",
  woman_basketball_jersey: "in a basketball court",
  soccer: "in a soccer field stadium",
  tennis: "on a tennis court",
  swimsuit: "near a swimming pool",
  sport: "at a gym",
  wedding_dress: "in a summer garden",
  fancy_dress: "in a summer garden",
  witch: "in the forest",
  summer_dress: "in a summer garden",
  lingerie: "in a bedroom",
  latex_outfit: "on a fashion show runway stage",
  princess_dress: "in a castle",
  corset: "at a historical reenactment",
  angel: "at a fantasy themed event",
  maid: "in a luxurious mansion",
  woman_medieval_armor: "at a medieval fair",
  lab_coat: "in a science laboratory",
  cowboy: "on a ranch",
  carnival: "at a carnival",
  casual: "in a casual dining restaurant",
  nurse: "in a hospital",
  santa_clauss: "at a Christmas event",
  police: "in a police station",
  steampunk: "at a steampunk convention",
  superhero: "on a modern street",
  teacher: "in a classroom",
  viking: "at a Viking festival",
  firefighter: "at a fire station",
  military: "at a military base",
  construction: "at a construction site",
  long_coat: "on a windy street",
  hoodie: "in an urban skate park",
  jeans: "in a casual setting",
  leggings: "at a yoga studio",
  ninja: "in a dojo",
  pyjamas: "at a cozy home",
  clown: "at a circus",
  barista: "in a coffee shop",
  belly_dancer: "at a cultural festival",
  goth: "in a gothic cathedral",
  pirate: "on a pirate ship",
  prisoner: "in a prison",
  race_driver: "at a race track",
  hijab: "in a cultural center",
  tutu: "in a ballet studio",
  poncho: "in a mountainous region",
  hiphop: "in a street dance competition",
  lumberjack: "in a forest",
  adventurer: "in a jungle",
  sailor: "on a ship",
  golf: "on a golf course",
  onesie: "at a sleepover party",
  oversized_shirt: "in a casual living room",
  tribal: "at a tribal village",
  secretary: "in an office",
  pop_star: "on a concert stage",
  pilot: "at the airport",
  builder: "on a construction site",
  monk: "at the park",
};

const defaultLocation: string[] = [
  "a serene beach at sunset",
  "a bustling city park",
  "a quiet mountain view",
  "a lively street festival",
  "a peaceful lakeside",
  "a snowy landscape",
  "a tropical rainforest",
  "a historical European town",
  "a desert under starlight",
  "a colorful botanical garden",
];

export const handleLocation = (clothes: string): string => {
  return (
    locationMap[clothes] ||
    defaultLocation[randomNumber(defaultLocation.length)]
  );
};
